### ISSUE TITLE
Helm default value for image tag

### ISSUE THREAD

**Issue by naeriaf** [planetlabs/draino#100]
The default image tag in the helm chart for the docker image tag seems to be broken, I would suggest changing it from `2c3d2b4` to `450a853`.

The error encountered when trying to run with the old image tag is this one: https://github.com/planetlabs/draino/issues/85

**Comment by bilalcaliskan** [comment]
@naeriaf if you use [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/#specification) patterns in your PR's, it will automatically close linked issue. for example:

```
fixes #100: draino helm image tag updated
```
