### ISSUE TITLE
Does draino plan to release? 

### ISSUE THREAD

**Issue by wanghh2000** [planetlabs/draino#19]
Hi, I am using draino, do you have a plan to the first release date?

**Comment by negz** [comment]
Hi @wanghh2000,

Thanks for using Draino! Historically we've used CI/CD in which every master commit is considered a 'release' and pushed to [the Docker hub](https://hub.docker.com/r/negz/draino/). I'm in the process of pointing the CI at `planetlabs/draino` instead, but the existing builds at `negz/draino` can be considered a release.

**Comment by negz** [comment]
I've added a Github release to make this more obvious. - https://github.com/planetlabs/draino/releases/tag/e0f16a4

I suspect there's another discussion to be had about whether we adopt semantic versioning and how that will tie to our current CI/CD strategy. Please open a separate issue if that's what you're looking for.
