### ISSUE TITLE
images published on docker hub does not have latest tag <eom>

### ISSUE THREAD

**Issue by maxormo** [planetlabs/draino#26]

**Comment by maxormo** [comment]
just tried:

> docker run planetlabs/draino /draino --help
> Unable to find image 'planetlabs/draino:latest' locally
> docker: Error response from daemon: manifest for planetlabs/draino:latest not found.
> See 'docker run --help'.

i believe in push script with `docker push "planetlabs/draino:${VERSION}"` you overwrite latest tag

**Comment by negz** [comment]
> i believe in push script with docker push "planetlabs/draino:${VERSION}" you overwrite latest tag

I'm pretty sure that's not the case. I'm hoping that next time a PR is merged the `latest` tag will be pushed.

**Comment by jacobstr** [comment]
I am a bad person and simply re-tagged the the existing image when doing the initial migration. We tend to avoid `latest` and didn't notice. I've since fixed some settings on the travis end, rebuilt, and confirmed I can successfully `docker pull planetlabs/draino:latest`.
