### ISSUE TITLE
Support for uncordon?

### ISSUE THREAD

**Issue by gtorre** [planetlabs/draino#27]
Hi, we're trying out draino and it seems to work well when testing. Our use case looks something like this:

- We have an asset management system that tracks the status of our bare metal assets. We can move a server manually through various states, ex. unallocated, maintenance, allocated.
- We want to be able to place a server (kubelet) in maintenance mode, and use NPD with a custom plugin to check this status, and then use draino to cordon and drain kubelets.
- When we move the server (kubelet) back to allocated, NPD will update the condition, but draino doesn't do anything about it.

Is the expectation that we use some other system to uncordon kubelets and make them available again to the cluster?

**Comment by cezarsa** [comment]
I'm willing to work on this issue. I'll draft something based on @negz idea of an annotation with the conditions and send a PR shortly.
