### ISSUE TITLE
support for node conditions with other flags than true?

### ISSUE THREAD

**Issue by maxormo** [planetlabs/draino#33]
Currently, draino supports only conditions with the status flag set to True. How about to support other possible values
like OutOfDisk=False.
Here is the sample of node conditions where I would like to draino to step in and drain them: 

Type             Status    
----             ------    
OutOfDisk        Unknown  
MemoryPressure   Unknown  
DiskPressure     Unknown  
PIDPressure      False     
Ready            Unknown  

or

Type                 Status  
----                 ------
NetworkUnavailable   False
OutOfDisk            False
MemoryPressure       False
DiskPressure         False
PIDPressure          False
Ready                False

The main purpose of my use case for draino is to change the node if it is not ready.

Any thoughts objectives?

**Comment by negz** [comment]
@maxormo Do I understand correctly that you'd like to have Draino drain nodes with condition `Ready: False` (and possibly `Ready: Unknown`)?

I'm not immediately opposed to this, but we might want to review the cases in which `Ready` is not `True`. I recall that nodes tend to go through `Ready: Unknown` as they initially join the cluster, in which case we probably don't want Draino to drain them.

**Comment by maxormo** [comment]
That is correct i would like to be able to drain node on `Ready: False` status. I will prepare PR

**Comment by jacobstr** [comment]
@maxormo I'd love to see a motivating example that you're encountering where:
- The node has a status of `Ready: False`.
- The node does not have a relevant _NodeCondition_ set to `True`.

> The main purpose of my use case for draino is to change the node if it is not ready.

If you could share how you're bringing up nodes and clusters and how frequently you see nodes with `Ready:False` that need to get torn down, that would be appreciated.

My fear with `Ready:False` is that unlike the conditions imparted by the _node-problem-detector_, `Ready:False` may trip for a variety of non-permanent, temporary conditions. In such cases draino may cause harm by:
- Shooting nodes that are booting up.
- Shooting nodes that are recoverable.

I'm generally paranoid about making it easier for draino to kill nodes.

**Comment by maxormo** [comment]
Node state `Ready=False` is a bad  example. I would consider it as a last resort. Better example is `OutOfDisk=Unknown` for me it was real production issue when several nodes went to not ready state because of full disk, in that case draining the node would resolve the issue by it self. The only concern I have is that I would like to know what exactly condition is caused node to be drained but it worth separate discussion.

As for how to avoid shooting nodes right after start I think draino need similar functionality as autoscaler where it see particular condition for some time and only after time threshold apply cordone and drain.

**Comment by dbenque** [comment]
On question about using `Ready=Unknown,10m` : if the node is in `unknown` state this means that the kubelet for that node is unresponsive, not sending heartbeat. Under such case it is unlikely that the `drain` activity can be completed: the kubelet cannot report that the pod is stopped (pod also will be in unknown).
Could you register cases where such `Ready=Unknown` condition have trigger a complete successful draino flow (cordon+drain) ?
