### ISSUE TITLE
Support leader election

### ISSUE THREAD

**Issue by negz** [planetlabs/draino#39]
```
// TODO(negz): Use leader election? We don't really want more than one draino
// running at a time.
// https://godoc.org/k8s.io/client-go/tools/leaderelection
```
Per [the above comment](https://github.com/planetlabs/draino/blob/master/cmd/draino/draino.go#L40) it would be nice if Draino used leader election to ensure that only one process was active at a time. Currently when many identically configured Draino processes run within the same cluster they'll race to cordon and drain any broken nodes they see. I'm fairly sure this would be harmless, but would produce confusing logs, metrics, and events.

**Comment by jacobstr** [comment]
We might want this if we tackle things like #27.
