### ISSUE TITLE
Running into unexpected failure when running.

### ISSUE THREAD

**Issue by CAR6807** [planetlabs/draino#40]
Kubernetes Version 1.12.6
My existing deployment of draino is crashing with the below error. 
Any good way to debug this further.

command 
    Command:
      /draino
      --debug
      --node-label=draino-enabled=true
      --node-label=node-problem-detector=true
      --drain-buffer=7m0s
      --evict-daemonset-pods
      --evict-unreplicated-pods
      --evict-emptydir-pods
      OutOfDisk
      MemoryPressure
      DiskPressure
      PIDPressure

`goroutine 1 [running]:
main.await.func2(0x0, 0x0)
	/go/src/github.com/planetlabs/draino/cmd/draino/draino.go:152 +0x2a
github.com/planetlabs/draino/vendor/github.com/oklog/run.(*Group).Run(0xc4201a1bb0, 0xc420418320, 0x1)
	/go/src/github.com/planetlabs/draino/vendor/github.com/oklog/run/group.go:47 +0x137
main.await(0xc4201a1f58, 0x2, 0x2, 0x1, 0x1)
	/go/src/github.com/planetlabs/draino/cmd/draino/draino.go:154 +0x248
main.main()
	/go/src/github.com/planetlabs/draino/cmd/draino/draino.go:140 +0x2121
command terminated with exit code 2`

kubectl logs

E0228 20:24:15.301957       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""

**Comment by jacobstr** [comment]
We're not providing a ton of useful context in our logs up to that point are way? :) I think I want to see more output from client go, but we set the log level to `0` [here](https://github.com/planetlabs/draino/blob/master/cmd/draino/draino.go#L182).

I'll try to spare a moment to push a configurable log level there to help get more visibility. In the meantime, I'm curious if this is happening intermittently or immediately on startup?

**Comment by CAR6807** [comment]
Seems to happen intermittently and on startup. However it seems to be working, just those odd logs every now and then. Im going to close this issue for now. But thanks for the quick response.
