### ISSUE TITLE
Drain schedule lost on restart

### ISSUE THREAD

**Issue by ivan-gusev** [planetlabs/draino#63]
Looks like drain schedule is not persisted between restarts and only time drain is scheduled is when node is transitioned from uncordoned into cordoned state. It effectively means that if draino is restarted it won't ever drain nodes that were cordoned in previous run.

**Comment by ivan-gusev** [comment]
Just as reference point preemptible node killer uses node annotation to store scheduled kill time
https://github.com/estafette/estafette-gke-preemptible-killer

**Comment by negz** [comment]
@ivan-gusev That sounds like a good design; I think we'd be happy to accept a PR for that for Draino if anyone is interested.

**Comment by dbenque** [comment]
I was about to open the same kind of issue, so I can work on that one.
My initial idea was to put this as a condition and not an annotation. The reason for that choice would be that Draino is working on conditions, that have nice display on a `kubectl describe` and we would see the condition that has triggered the drain and the drain scheduling in the same table.

When draino controller restarts it should know that a drain has to be requested/scheduled but this new instance of the controller has to decide the WHEN. This WHEN cannot dictated by a previous instance of the controller via a value in an annotation. The given WHEN could be in the past, also the parameters of the new controller instance may have change and may lead to a new scheduling plan.

Is there any code started around that issue ? @ivan-gusev

**Comment by jacobstr** [comment]
Merged @dbenque's contribution to resolve this issue.
