### ISSUE TITLE
Filter for pods created by StatefulSet

### ISSUE THREAD

**Issue by dbenque** [planetlabs/draino#69]
Applications that use StatefulSet usually come with some complexity and deserve particular attention.

In our particular case we would like to use Draino on every node and workload that are not behind StatefulSet. That represents a huge part of our system where Draino can bring value. StatefulSet will need more logic probably in a dedicated operator for each application.

I can provide a PR to support such filtering.

**Comment by jacobstr** [comment]
Thanks @dbenque
