### ISSUE TITLE
Consider Cluster-Autoscaler `safe-to-evict` annotation by default

### ISSUE THREAD

**Issue by dbenque** [planetlabs/draino#73]
Draino should not evict pods that are marked with 
"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

I can do the PR if there is an agreement on that.

**Comment by jacobstr** [comment]
Sounds like a net win vs. the coarse approach of opting in to evict-daemonset/evict-statefulset etc.
