### ISSUE TITLE
Immutable draino - failure

### ISSUE THREAD

**Issue by oronboni** [planetlabs/draino#79]
One of the security requirement is immutable (container level configuration)

https://cloud.google.com/solutions/best-practices-for-operating-containers#ensure_that_your_containers_are_stateless_and_immutable

In order the container will be immutable those configurations the configuration below required (in container level):
```
securityContext:
  privileged: false
  readOnlyRootFilesystem: true
```
Adding that configuration to the chart leads to the following error:
log: exiting because of error: log: cannot create log: open /tmp/draino.node-remediation-draino-668456857d-zdj2n.user.log.INFO.20200803-132414.1: read-only file system

**Comment by jacobstr** [comment]
Can you try this `securityContext` in another pod on your cluster that emits logs? The logs should be written to stdout not `/tmp`.
